<?php

namespace ContainerS0pDk0i;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitacionesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\HabitacionesType' shared autowired service.
     *
     * @return \App\Form\HabitacionesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\AbstractType.php';
        include_once \dirname(__DIR__, 4).'\\src\\Form\\HabitacionesType.php';

        return $container->privates['App\\Form\\HabitacionesType'] = new \App\Form\HabitacionesType();
    }
}
