<?php

namespace ContainerS0pDk0i;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPerfilControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PerfilController' shared autowired service.
     *
     * @return \App\Controller\PerfilController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
        include_once \dirname(__DIR__, 4).'\\src\\Controller\\PerfilController.php';

        $container->services['App\\Controller\\PerfilController'] = $instance = new \App\Controller\PerfilController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\PerfilController', $container));

        return $instance;
    }
}
