<?php

namespace ContainerW2jyB2W;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SrLf9iHService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.srLf9iH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.srLf9iH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cliente' => ['privates', '.errored..service_locator.srLf9iH.App\\Entity\\Clientes', NULL, 'Cannot autowire service ".service_locator.srLf9iH": it references class "App\\Entity\\Clientes" but no such service exists.'],
        ], [
            'cliente' => 'App\\Entity\\Clientes',
        ]);
    }
}
