<?php

namespace ContainerW2jyB2W;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientesService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.srLf9iH.App\Entity\Clientes' shared service.
     *
     * @return \App\Entity\Clientes
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.srLf9iH": it references class "App\\Entity\\Clientes" but no such service exists.');
    }
}
