<?php

namespace ContainerW2jyB2W;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitacionesService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eqnmxvT.App\Entity\Habitaciones' shared service.
     *
     * @return \App\Entity\Habitaciones
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.eqnmxvT": it references class "App\\Entity\\Habitaciones" but no such service exists.');
    }
}
