easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
        - App\Entity\Clientes
        - App\Entity\Comentarioshospedaje
        - App\Entity\Habitaciones
        - App\Entity\Hospedaje
        - App\Entity\Multimedia
        - App\Entity\Perfil
        - App\Entity\Proveedores
        - App\Entity\Reservas
        - App\Entity\Servicios
        - App\Entity\Servicioshabitaciones
        - App\Entity\Tipohospedaje
