<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1zW0fg1\App_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1zW0fg1/App_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/Container1zW0fg1.legacy');

    return;
}

if (!\class_exists(App_KernelEnvDebugContainer::class, false)) {
    \class_alias(\Container1zW0fg1\App_KernelEnvDebugContainer::class, App_KernelEnvDebugContainer::class, false);
}

return new \Container1zW0fg1\App_KernelEnvDebugContainer([
    'container.build_hash' => '1zW0fg1',
    'container.build_id' => 'b71dadb7',
    'container.build_time' => 1606241121,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1zW0fg1');
