<?php

namespace ContainerR7U861H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DILx7bjService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.dILx7bj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dILx7bj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'habitacionesRepository' => ['privates', 'App\\Repository\\HabitacionesRepository', 'getHabitacionesRepositoryService', true],
        ], [
            'habitacionesRepository' => 'App\\Repository\\HabitacionesRepository',
        ]);
    }
}
