<?php

namespace ContainerR7U861H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientesRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ClientesRepository' shared autowired service.
     *
     * @return \App\Repository\ClientesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ClientesRepository'] = new \App\Repository\ClientesRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
