<?php

namespace ContainerR7U861H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComentarioshospedajeService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.UHwoknX.App\Entity\Comentarioshospedaje' shared service.
     *
     * @return \App\Entity\Comentarioshospedaje
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.UHwoknX": it references class "App\\Entity\\Comentarioshospedaje" but no such service exists.');
    }
}
