<?php

namespace ContainerR7U861H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMultimediaTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\MultimediaType' shared autowired service.
     *
     * @return \App\Form\MultimediaType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\MultimediaType'] = new \App\Form\MultimediaType();
    }
}
