<?php

namespace ContainerR7U861H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_EventDispatcher_Main_EventBubblingListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.event_dispatcher.main.event_bubbling_listener' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\EventListener\FirewallEventBubblingListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.event_dispatcher.main.event_bubbling_listener'] = new \Symfony\Bundle\SecurityBundle\EventListener\FirewallEventBubblingListener(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
    }
}
