<?php

namespace ContainerR7U861H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiciosControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ServiciosController' shared autowired service.
     *
     * @return \App\Controller\ServiciosController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ServiciosController'] = $instance = new \App\Controller\ServiciosController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\ServiciosController', $container));

        return $instance;
    }
}
