<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR7U861H\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR7U861H/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerR7U861H.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerR7U861H\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerR7U861H\App_KernelProdContainer([
    'container.build_hash' => 'R7U861H',
    'container.build_id' => 'c002f6f9',
    'container.build_time' => 1605547657,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR7U861H');
