<?php

namespace Container1zW0fg1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TqZlqUDService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.tqZlqUD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tqZlqUD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'serviciosRepository' => ['privates', 'App\\Repository\\ServiciosRepository', 'getServiciosRepositoryService', true],
        ], [
            'serviciosRepository' => 'App\\Repository\\ServiciosRepository',
        ]);
    }
}
