<?php

namespace Container1zW0fg1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiciosService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ACVLdjH.App\Entity\Servicios' shared service.
     *
     * @return \App\Entity\Servicios
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ACVLdjH": it references class "App\\Entity\\Servicios" but no such service exists.');
    }
}
