<?php

namespace Container1zW0fg1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTipohospedajeService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SO67mA5.App\Entity\Tipohospedaje' shared service.
     *
     * @return \App\Entity\Tipohospedaje
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.SO67mA5": it references class "App\\Entity\\Tipohospedaje" but no such service exists.');
    }
}
