<?php

namespace ContainerYSqT0SV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPerfilService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZJ8.Xeu.App\Entity\Perfil' shared service.
     *
     * @return \App\Entity\Perfil
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ZJ8.Xeu": it references class "App\\Entity\\Perfil" but no such service exists.');
    }
}
