<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Habitaciones extends \App\Entity\Habitaciones implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'numadultos', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'numinfantiles', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'nummascotas', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'mediavaloracion', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'mediavaloracionmascotas', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'numcomentarios', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'precio', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'fechacreacion', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'activo', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'idhospedaje'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'numadultos', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'numinfantiles', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'nummascotas', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'mediavaloracion', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'mediavaloracionmascotas', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'numcomentarios', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'precio', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'fechacreacion', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'activo', '' . "\0" . 'App\\Entity\\Habitaciones' . "\0" . 'idhospedaje'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Habitaciones $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): \App\Entity\Habitaciones
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumadultos(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumadultos', []);

        return parent::getNumadultos();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumadultos(int $numadultos): \App\Entity\Habitaciones
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumadultos', [$numadultos]);

        return parent::setNumadultos($numadultos);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuminfantiles(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuminfantiles', []);

        return parent::getNuminfantiles();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuminfantiles(int $numinfantiles): \App\Entity\Habitaciones
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuminfantiles', [$numinfantiles]);

        return parent::setNuminfantiles($numinfantiles);
    }

    /**
     * {@inheritDoc}
     */
    public function getNummascotas(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNummascotas', []);

        return parent::getNummascotas();
    }

    /**
     * {@inheritDoc}
     */
    public function setNummascotas(int $nummascotas): \App\Entity\Habitaciones
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNummascotas', [$nummascotas]);

        return parent::setNummascotas($nummascotas);
    }

    /**
     * {@inheritDoc}
     */
    public function getMediavaloracion(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMediavaloracion', []);

        return parent::getMediavaloracion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMediavaloracion(?float $mediavaloracion): \App\Entity\Habitaciones
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMediavaloracion', [$mediavaloracion]);

        return parent::setMediavaloracion($mediavaloracion);
    }

    /**
     * {@inheritDoc}
     */
    public function getMediavaloracionmascotas(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMediavaloracionmascotas', []);

        return parent::getMediavaloracionmascotas();
    }

    /**
     * {@inheritDoc}
     */
    public function setMediavaloracionmascotas(?float $mediavaloracionmascotas): \App\Entity\Habitaciones
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMediavaloracionmascotas', [$mediavaloracionmascotas]);

        return parent::setMediavaloracionmascotas($mediavaloracionmascotas);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumcomentarios(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumcomentarios', []);

        return parent::getNumcomentarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumcomentarios(?int $numcomentarios): \App\Entity\Habitaciones
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumcomentarios', [$numcomentarios]);

        return parent::setNumcomentarios($numcomentarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', []);

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio(float $precio): \App\Entity\Habitaciones
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', [$precio]);

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechacreacion(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechacreacion', []);

        return parent::getFechacreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechacreacion(\DateTimeInterface $fechacreacion): \App\Entity\Habitaciones
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechacreacion', [$fechacreacion]);

        return parent::setFechacreacion($fechacreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo(bool $activo): \App\Entity\Habitaciones
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdhospedaje(): ?\App\Entity\Hospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdhospedaje', []);

        return parent::getIdhospedaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdhospedaje(?\App\Entity\Hospedaje $idhospedaje): \App\Entity\Habitaciones
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdhospedaje', [$idhospedaje]);

        return parent::setIdhospedaje($idhospedaje);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
