<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Hospedaje extends \App\Entity\Hospedaje implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'direccion', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'ciudad', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'fechacreacion', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'activo', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'admin1code', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'admin2code', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'admin3code', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'admin4code', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'idproveedor', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'idtipohospedaje'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'direccion', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'ciudad', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'fechacreacion', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'activo', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'admin1code', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'admin2code', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'admin3code', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'admin4code', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'idproveedor', '' . "\0" . 'App\\Entity\\Hospedaje' . "\0" . 'idtipohospedaje'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Hospedaje $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): \App\Entity\Hospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion(string $descripcion): \App\Entity\Hospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion(string $direccion): \App\Entity\Hospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', []);

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad(string $ciudad): \App\Entity\Hospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', [$ciudad]);

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono(string $telefono): \App\Entity\Hospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Hospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechacreacion(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechacreacion', []);

        return parent::getFechacreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechacreacion(\DateTimeInterface $fechacreacion): \App\Entity\Hospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechacreacion', [$fechacreacion]);

        return parent::setFechacreacion($fechacreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo(bool $activo): \App\Entity\Hospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmin1code(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmin1code', []);

        return parent::getAdmin1code();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmin1code(?string $admin1code): \App\Entity\Hospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmin1code', [$admin1code]);

        return parent::setAdmin1code($admin1code);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmin2code(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmin2code', []);

        return parent::getAdmin2code();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmin2code(?string $admin2code): \App\Entity\Hospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmin2code', [$admin2code]);

        return parent::setAdmin2code($admin2code);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmin3code(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmin3code', []);

        return parent::getAdmin3code();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmin3code(?string $admin3code): \App\Entity\Hospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmin3code', [$admin3code]);

        return parent::setAdmin3code($admin3code);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmin4code(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmin4code', []);

        return parent::getAdmin4code();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmin4code(?string $admin4code): \App\Entity\Hospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmin4code', [$admin4code]);

        return parent::setAdmin4code($admin4code);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdproveedor(): ?\App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdproveedor', []);

        return parent::getIdproveedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdproveedor(?\App\Entity\Clientes $idproveedor): \App\Entity\Hospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdproveedor', [$idproveedor]);

        return parent::setIdproveedor($idproveedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtipohospedaje(): ?\App\Entity\Tipohospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipohospedaje', []);

        return parent::getIdtipohospedaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtipohospedaje(?\App\Entity\Tipohospedaje $idtipohospedaje): \App\Entity\Hospedaje
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtipohospedaje', [$idtipohospedaje]);

        return parent::setIdtipohospedaje($idtipohospedaje);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
