<?php

namespace ContainerCbkscwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UHwoknXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UHwoknX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UHwoknX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comentarioshospedaje' => ['privates', '.errored..service_locator.UHwoknX.App\\Entity\\Comentarioshospedaje', NULL, 'Cannot autowire service ".service_locator.UHwoknX": it references class "App\\Entity\\Comentarioshospedaje" but no such service exists.'],
        ], [
            'comentarioshospedaje' => 'App\\Entity\\Comentarioshospedaje',
        ]);
    }
}
