<?php

namespace ContainerCbkscwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SO67mA5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SO67mA5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SO67mA5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tipohospedaje' => ['privates', '.errored..service_locator.SO67mA5.App\\Entity\\Tipohospedaje', NULL, 'Cannot autowire service ".service_locator.SO67mA5": it references class "App\\Entity\\Tipohospedaje" but no such service exists.'],
        ], [
            'tipohospedaje' => 'App\\Entity\\Tipohospedaje',
        ]);
    }
}
