<?php

namespace ContainerCbkscwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMultimediaTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MultimediaType' shared autowired service.
     *
     * @return \App\Form\MultimediaType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/MultimediaType.php';

        return $container->privates['App\\Form\\MultimediaType'] = new \App\Form\MultimediaType();
    }
}
