<?php

namespace ContainerJuFGU9a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHospedajeService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Y.FqaH_.App\Entity\Hospedaje' shared service.
     *
     * @return \App\Entity\Hospedaje
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Y.FqaH_": it references class "App\\Entity\\Hospedaje" but no such service exists.');
    }
}
