<?php

namespace ContainerJuFGU9a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservasService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Bmzu9Fg.App\Entity\Reservas' shared service.
     *
     * @return \App\Entity\Reservas
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Bmzu9Fg": it references class "App\\Entity\\Reservas" but no such service exists.');
    }
}
