<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Autocomplete extends \App\Entity\Autocomplete implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'textobusqueda', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'tipo', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'admin1code', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'admin2code', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'admin3code', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'admin4code', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'idhospedaje'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'textobusqueda', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'tipo', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'admin1code', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'admin2code', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'admin3code', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'admin4code', '' . "\0" . 'App\\Entity\\Autocomplete' . "\0" . 'idhospedaje'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Autocomplete $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTextobusqueda(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextobusqueda', []);

        return parent::getTextobusqueda();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextobusqueda(string $textobusqueda): \App\Entity\Autocomplete
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextobusqueda', [$textobusqueda]);

        return parent::setTextobusqueda($textobusqueda);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo(string $tipo): \App\Entity\Autocomplete
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmin1code(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmin1code', []);

        return parent::getAdmin1code();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmin1code(?string $admin1code): \App\Entity\Autocomplete
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmin1code', [$admin1code]);

        return parent::setAdmin1code($admin1code);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmin2code(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmin2code', []);

        return parent::getAdmin2code();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmin2code(?string $admin2code): \App\Entity\Autocomplete
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmin2code', [$admin2code]);

        return parent::setAdmin2code($admin2code);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmin3code(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmin3code', []);

        return parent::getAdmin3code();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmin3code(?string $admin3code): \App\Entity\Autocomplete
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmin3code', [$admin3code]);

        return parent::setAdmin3code($admin3code);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmin4code(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmin4code', []);

        return parent::getAdmin4code();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmin4code(?string $admin4code): \App\Entity\Autocomplete
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmin4code', [$admin4code]);

        return parent::setAdmin4code($admin4code);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdhospedaje(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdhospedaje', []);

        return parent::getIdhospedaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdhospedaje(?int $idhospedaje): \App\Entity\Autocomplete
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdhospedaje', [$idhospedaje]);

        return parent::setIdhospedaje($idhospedaje);
    }

}
